/**
 * lib/seo.ts
 * Central SEO utilities: slug generation, metadata factories, JSON-LD builders.
 * Import from here everywhere — never duplicate SEO logic across pages.
 */

import type { Metadata } from 'next';

// ─────────────────────────────────────────────
// 1. CONSTANTS
// ─────────────────────────────────────────────

const RAW_SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ||
  process.env.SITE_URL ||
  'http://localhost:3000';

export const SITE_URL = RAW_SITE_URL.startsWith('http')
  ? RAW_SITE_URL
  : `https://${RAW_SITE_URL}`;

export const BRAND_NAME = 'IKNA';
export const DEFAULT_OG_IMAGE = '/images/AI_images/logo1_ikna.png';

// Per-category SEO copy. Keys are lower-cased category names.
const CATEGORY_COPY: Record<
  string,
  { h1: string; title: string; description: string }
> = {
  bras: {
    h1: 'Bras – Comfort-First Collection',
    title: 'Buy Bras Online India | Wirefree, Padded & Seamless Bras | IKNA',
    description:
      'Shop IKNA bras online — wirefree, padded, seamless and everyday bras designed for all-day comfort. Premium quality, honest pricing. Free shipping available across India.',
  },
  panties: {
    h1: "Panties \u2013 Women's Everyday Collection",
    title: 'Buy Panties Online India | Bikini, Hipster & Boyshorts | IKNA',
    description:
      'Explore IKNA panties — bikini, hipster, boyshorts and thongs crafted from skin-friendly, breathable fabrics. Inclusive sizing, comfortable fit. Shop now.',
  },
  briefs: {
    h1: 'Briefs – Comfort & Coverage',
    title: "Buy Briefs Online India | Women's Full Coverage Briefs | IKNA",
    description:
      'Shop IKNA briefs designed for all-day coverage and comfort. Soft, breathable fabrics and a secure fit. Free shipping across India.',
  },
  sets: {
    h1: 'Lingerie Sets – Matching Bra & Panty Sets',
    title: 'Buy Lingerie Sets Online India | Matching Bra & Panty Sets | IKNA',
    description:
      "Explore IKNA's matching lingerie sets \u2014 coordinated bra and panty pairs crafted for comfort and style. Shop coordinated sets online.",
  },
};

// ─────────────────────────────────────────────
// 2. URL HELPERS
// ─────────────────────────────────────────────

/** Returns a fully-qualified canonical URL for the given path. */
export function buildCanonical(path: string): string {
  const normalised = path.startsWith('/') ? path : `/${path}`;
  return `${SITE_URL}${normalised}`;
}

// ─────────────────────────────────────────────
// 3. SLUG UTILITIES
// ─────────────────────────────────────────────

function toSlugBase(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')   // strip non-alphanumeric (keep hyphens + spaces)
    .replace(/\s+/g, '-')           // spaces → hyphens
    .replace(/-+/g, '-')            // collapse multiple hyphens
    .replace(/^-+|-+$/g, '');       // trim leading/trailing hyphens
}

/**
 * Generates a human-readable, SEO-friendly product slug.
 * Format: {name-slug}-{color-slug}-{cuid}
 * Example: grace-wirefree-padded-cotton-bra-grey-cm9x7abcdefghijklmnopqr
 *
 * The cuid suffix ensures uniqueness without a DB lookup and allows
 * the server to extract the ID from the slug for fast queries.
 */
export function generateProductSlug(product: {
  name: string;
  colorName?: string | null;
  id: string;
}): string {
  const parts = [product.name, product.colorName].filter(Boolean).join(' ');
  const base = toSlugBase(parts);
  return `${base}-${product.id}`;
}

/**
 * Extracts the product ID from a slug generated by generateProductSlug.
 * Falls back to treating the entire string as an ID (backward-compat with
 * old /product/[cuid] URLs that link directly to a bare ID).
 *
 * cuid IDs are 25 lowercase alphanumeric chars (no hyphens).
 */
export function extractIdFromSlug(slug: string): string {
  const parts = slug.split('-');
  const last = parts[parts.length - 1];
  // For generated product slugs, the real ID is always the trailing segment.
  // This supports short numeric IDs, old cuid IDs, and future alphanumeric IDs.
  if (parts.length > 1 && last) {
    return last;
  }
  // Legacy: whole slug is a bare cuid
  return slug;
}

// ─────────────────────────────────────────────
// 4. METADATA FACTORIES
// ─────────────────────────────────────────────

export interface ProductSeoData {
  id: string;
  name: string;
  description?: string | null;
  price: number | string | { toNumber?: () => number };
  image?: string | null;
  colorName?: string | null;
  fabricType?: string | null;
  stock?: number;
  images?: Array<{ image_path: string; is_primary?: boolean | null }>;
  productType?: { name: string; slug?: string } | null;
  subCategory?: { name: string; slug?: string } | null;
}

function resolvePrice(price: ProductSeoData['price']): string {
  if (typeof price === 'object' && price !== null && typeof (price as any).toNumber === 'function') {
    return String((price as any).toNumber());
  }
  return String(price ?? '');
}

/** Generates rich Metadata for a product page. */
export function generateProductMetadata(product: ProductSeoData): Metadata {
  const slug = generateProductSlug(product);
  const canonical = buildCanonical(`/product/${slug}`);
  const categoryName =
    product.subCategory?.name ||
    product.productType?.name ||
    'Lingerie';

  const title = `${product.name}${product.colorName ? ` – ${product.colorName}` : ''} | IKNA`;
  const description =
    product.description
      ? `${product.description.slice(0, 140).trimEnd()}… Buy online from IKNA.`
      : `Shop ${product.name} by IKNA — premium ${categoryName.toLowerCase()} designed for all-day comfort. Free shipping across India.`;

  const ogImage = product.images?.find((img) => img.is_primary)?.image_path ||
    product.image ||
    DEFAULT_OG_IMAGE;

  return {
    title,
    description,
    keywords: [
      product.name,
      categoryName,
      BRAND_NAME,
      'buy online India',
      product.colorName ?? '',
      product.fabricType ?? '',
    ].filter(Boolean),
    alternates: { canonical },
    openGraph: {
      title,
      description,
      url: canonical,
      siteName: BRAND_NAME,
      type: 'website',
      images: [{ url: ogImage, alt: product.name }],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage],
    },
  };
}

/** Generates Metadata for a category (e.g. /shop/Bras). */
export function generateCategoryMetadata(
  rawCategory: string,
  subcategory?: string,
): Metadata {
  const key = rawCategory.toLowerCase();
  const copy = CATEGORY_COPY[key];

  const displayName = rawCategory.charAt(0).toUpperCase() + rawCategory.slice(1);
  const subDisplay = subcategory
    ? ` – ${subcategory.charAt(0).toUpperCase() + subcategory.slice(1)}`
    : '';

  const title = copy
    ? copy.title
    : `Buy ${displayName} Online India | ${BRAND_NAME}${subDisplay}`;

  const description = copy
    ? copy.description
    : `Shop ${displayName}${subDisplay} from IKNA — premium lingerie crafted for everyday comfort. Free shipping across India.`;

  const canonical = buildCanonical(
    subcategory
      ? `/shop/${encodeURIComponent(rawCategory)}?search=${encodeURIComponent(subcategory)}`
      : `/shop/${encodeURIComponent(rawCategory)}`,
  );

  return {
    title,
    description,
    keywords: [
      `buy ${rawCategory.toLowerCase()} online India`,
      `${rawCategory.toLowerCase()} lingerie`,
      `${rawCategory.toLowerCase()} ${BRAND_NAME.toLowerCase()}`,
      'women innerwear India',
      subcategory ?? '',
    ].filter(Boolean),
    alternates: { canonical },
    openGraph: {
      title,
      description,
      url: canonical,
      siteName: BRAND_NAME,
      type: 'website',
      images: [{ url: DEFAULT_OG_IMAGE, alt: `${displayName} – ${BRAND_NAME}` }],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
    },
  };
}

// ─────────────────────────────────────────────
// 5. JSON-LD SCHEMA BUILDERS
// ─────────────────────────────────────────────

/** Product structured data (schema.org/Product). */
export function getProductJsonLd(
  product: ProductSeoData,
  canonicalUrl: string,
): object {
  const price = resolvePrice(product.price);
  const primaryImage =
    product.images?.find((img) => img.is_primary)?.image_path ||
    product.image ||
    DEFAULT_OG_IMAGE;

  const allImages = product.images?.length
    ? product.images.map((img) => img.image_path).filter(Boolean)
    : [primaryImage];

  const availability =
    (product.stock ?? 1) > 0
      ? 'https://schema.org/InStock'
      : 'https://schema.org/OutOfStock';

  return {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: product.name,
    description: product.description ?? '',
    image: allImages,
    brand: {
      '@type': 'Brand',
      name: BRAND_NAME,
    },
    category:
      product.subCategory?.name ||
      product.productType?.name ||
      'Lingerie',
    offers: {
      '@type': 'Offer',
      url: canonicalUrl,
      priceCurrency: 'INR',
      price,
      availability,
      seller: {
        '@type': 'Organization',
        name: BRAND_NAME,
        url: SITE_URL,
      },
    },
  };
}

/** BreadcrumbList structured data (schema.org/BreadcrumbList). */
export function getBreadcrumbJsonLd(
  items: Array<{ name: string; url?: string }>,
): object {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: item.name,
      ...(item.url ? { item: item.url } : {}),
    })),
  };
}

/** Organization/Website schema for use in the root layout. */
export function getOrganizationJsonLd(): object {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: BRAND_NAME,
    url: SITE_URL,
    logo: `${SITE_URL}/images/AI_images/logo1_ikna.png`,
    sameAs: [
      'https://instagram.com/ikna_official',
      'https://facebook.com',
    ],
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: '+91-98403-49375',
      contactType: 'customer service',
      areaServed: 'IN',
      availableLanguage: 'English',
    },
  };
}
